#! /usr/bin/env python3
"""
A program to receive data from the Subaru Telescope Gen2 system.

Typical use:

$ datasink -f <configfile>

where <configfile> is the path to a file containing the configuration
for this datasink.
"""
import sys
from argparse import ArgumentParser

from g2base import ssdlog

from datasink.datasink import main


if __name__ == '__main__':

    argprs = ArgumentParser("Gen2 datasink")

    argprs.add_argument("-f", "--config", dest="conffile",
                        help="Specify the configuration file for this sink")
    argprs.add_argument("--kill", dest="kill", action="store_true",
                        default=False,
                        help="Kill the running datasink")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if options.conffile is None:
        argprs.error("You need to specify a config file with -f")

    main(options, args)
