#! /usr/bin/env python
"""
  $ ds_sleep [sleep sec]

"""
import sys
import json


def main(options, args):
    if len(args) == 0:
        duration = 10.0
    else:
        duration = float(args[0])

    d = dict(action='sleep', duration=duration)

    print(json.dumps(d))

if __name__ == '__main__':

    # Parse command line options with nifty new optparse module
    from argparse import ArgumentParser

    argprs = ArgumentParser("JobSource sender")

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) > 1:
        argprs.error("Unrecognized arguments: {}".format(str(args)))

    main(options, args)
